[package]
name = "digital_test_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
getrandom = "0.2.12"
nom = "7.1.3"
nom_locate = "4.2.0"
rand = "0.8.5"
roxmltree = "0.19.0"

[dev-dependencies]
rstest = "0.18.2"
